[package]
name = "math_eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = { version = "3.0", default-features = false }

[profile.release]
opt-level = 3
lto = true
debug = false